name: covector version or publish
on:
  push:
    branches:
    - dev

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cargo login
        run: cargo login ${{ secrets.crate_token }}
      - name: covector version-or-publish
        uses: jbolda/covector/packages/action@covector-v0.1.1
        id: covector
        with:
          command: 'version-or-publish'
      - name: create pull request
        id: cpr
        uses: tauri-apps/create-pull-request@v2
        with:
          title: "Publish New Versions"
          labels: "version updates"
          branch: "release"
